### ISSUE TITLE
Issue putting Nova Rating fields in a SimpleRepeatable field

### ISSUE THREAD

**Issue by terry-greenlaw** [optimistdigital/nova-simple-repeatable#13]
I'm using Nova Rating package (https://github.com/nikaia/nova-rating-field) for fields inside of a SimpleRepeatable field. The edit page looks great, but on the detail page, the underlying values are displayed instead of the stars.

Further down on the same detail page, I am using the rating outside of a SimpleRepeatable, and the stars are displaying.

Working on the edit page:
![image](https://user-images.githubusercontent.com/49298815/114455336-a41bdd80-9ba9-11eb-90f5-4dd1e233ede9.png)

Showing the underlying value on the detail page:
![image](https://user-images.githubusercontent.com/49298815/114455479-cb72aa80-9ba9-11eb-9bf5-27e33bb52962.png)

Further down the edit page:
![image](https://user-images.githubusercontent.com/49298815/114455867-3623e600-9baa-11eb-93b0-d27df691972a.png)

**Comment by Tarpsvo** [comment]
Hi! So I've changed the detail view so it now renders the correct detail view component. This is not guaranteed to look good though and once I get reports about common fields looking really weird, I might have to rework some stuff and allow users to handpick which fields should render as themselves. But your ratings field should be fine I hope, please do give it a try. Good luck!
