### ISSUE TITLE
Validation Errors Issue

### ISSUE THREAD

**Issue by 29avet1** [optimistdigital/nova-simple-repeatable#14]
When you have roles attached to SimpleRepeatable Field anf you get a validation error that DOES NOT related to SimpleRepeatable filed, then you get an error

![image](https://user-images.githubusercontent.com/16347448/117436038-9571dd80-af3f-11eb-8f1a-ffaa9c3a7562.png)

TypeError: Cannot read property '0' of null
Seems in case we have validation error, it tries to get first validation error. but as that validation  error belongs to another filed, it tries to get first item from NULL, and that brakes the JS code.
In this case Sorting and "Add Row" don't work anymore, and also the data can't be saved anymore, even when validation error is fixed.

**Comment by 29avet1** [comment]
An Update, I checked and it return a JSON string, my validation was set to expect an Array, that's why it was broken.
But still there is an issue that Validation error "Extensions field must be an Array" is not shown here.

**Comment by Tarpsvo** [comment]
Heya! There was indeed an issue with validation keys parsing. It is now fixed in release 1.3.0. Do give it a try! Thanks for reporting this and good luck!
