### ISSUE TITLE
Translatable

### ISSUE THREAD

**Issue by mark2938** [optimistdigital/nova-simple-repeatable#15]
Hello, I couldn't run it with nova-translatable package. Always empty resolving.

**Comment by Tarpsvo** [comment]
Hi! Is the repeater inside Flexible content?

**Comment by Tarpsvo** [comment]
I made some recent updates to both fields, please try it out and report back if it's still not working. Thanks!

**Comment by nurmuhammet-ali** [comment]
Hey, @Tarpsvo I still cannot get it working with your translatable library. Sorry to bother by the way.

**Comment by Tarpsvo** [comment]
More info pls
