### ISSUE TITLE
Meta $maxRows not implemented in front-end

### ISSUE THREAD

**Issue by mikelgoig** [optimistdigital/nova-simple-repeatable#3]
Hi!

Is there any way to set the maximum number of rows?

I saw the "maxRows" function, but it is not used by the front-end component.

https://github.com/optimistdigital/nova-simple-repeatable/blob/8499dd4b2b0a9eb518edf623a3e14532d74464ac/src/SimpleRepeatable.php#L39

Thanks!

**Comment by Tarpsvo** [comment]
Ah yes, I indeed forgot to implement it on the Vue side. :) Fixed it now and released in version 1.1.2. Good luck!
