### ISSUE TITLE
HasMany SQLSTATE[42S22]: Column not found

### ISSUE THREAD

**Issue by Muetze42** [optimistdigital/nova-simple-repeatable#8]
I've this relation:
```php
HasMany::make(__('Answers'), 'answers', NumberReactionAnswer::class),
```

And this field works on index and edit:
```php
            SimpleRepeatable::make(__('Answers'), 'answers', [
                Textarea::make(__('Answer'), 'content')->required()->rules('required')->rows(2),
                Number::make('Min')->default(-100)->required()->rules('required')->step(0.001),
                Number::make('Max')->default(100)->required()->rules('required')->step(0.001),
            ])
                ->canAddRows(true)
                ->canDeleteRows(true),
```

But if I want to save, I get this error message:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'answers' in 'field list'`

**Comment by 29avet1** [comment]
@Muetze42 Unfortunately this package does not work with relations.
It returns only Array that can be saved as json field in db.

**Comment by Tarpsvo** [comment]
Hi! Yeah, that's a rather weird usecase. Theoretically you can override `->fillUsing(fn () => ...)` to manually attach/detach values from the `answers` relation, but there's no good way to create a unified way of doing this. :(

See this example from my nova-multiselect for an example:
https://github.com/optimistdigital/nova-multiselect-field/blob/master/src/Multiselect.php#L320
